<?php

namespace DoctrineORMModule\Proxy\__CG__\Base\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Agencia extends \Base\Entity\Agencia implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'idagencia', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'nome', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'razaoSocial', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'endereco', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cep', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'telefone', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'fax', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cnpj', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'inscrEstadual', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'inscrMunicipal', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'horarioComercial', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cidade', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'estado');
        }

        return array('__isInitialized__', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'idagencia', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'nome', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'razaoSocial', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'endereco', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cep', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'telefone', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'fax', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cnpj', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'inscrEstadual', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'inscrMunicipal', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'horarioComercial', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'cidade', '' . "\0" . 'Base\\Entity\\Agencia' . "\0" . 'estado');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Agencia $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdagencia()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdagencia();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdagencia', array());

        return parent::getIdagencia();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdagencia($idagencia)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdagencia', array($idagencia));

        return parent::setIdagencia($idagencia);
    }

    /**
     * {@inheritDoc}
     */
    public function getNome()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNome', array());

        return parent::getNome();
    }

    /**
     * {@inheritDoc}
     */
    public function setNome($nome)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNome', array($nome));

        return parent::setNome($nome);
    }

    /**
     * {@inheritDoc}
     */
    public function getRazaoSocial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRazaoSocial', array());

        return parent::getRazaoSocial();
    }

    /**
     * {@inheritDoc}
     */
    public function setRazaoSocial($razaoSocial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRazaoSocial', array($razaoSocial));

        return parent::setRazaoSocial($razaoSocial);
    }

    /**
     * {@inheritDoc}
     */
    public function getEndereco()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEndereco', array());

        return parent::getEndereco();
    }

    /**
     * {@inheritDoc}
     */
    public function setEndereco($endereco)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEndereco', array($endereco));

        return parent::setEndereco($endereco);
    }

    /**
     * {@inheritDoc}
     */
    public function getCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCep', array());

        return parent::getCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCep($cep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCep', array($cep));

        return parent::setCep($cep);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelefone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelefone', array());

        return parent::getTelefone();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelefone($telefone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelefone', array($telefone));

        return parent::setTelefone($telefone);
    }

    /**
     * {@inheritDoc}
     */
    public function getFax()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFax', array());

        return parent::getFax();
    }

    /**
     * {@inheritDoc}
     */
    public function setFax($fax)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFax', array($fax));

        return parent::setFax($fax);
    }

    /**
     * {@inheritDoc}
     */
    public function getCnpj()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCnpj', array());

        return parent::getCnpj();
    }

    /**
     * {@inheritDoc}
     */
    public function setCnpj($cnpj)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCnpj', array($cnpj));

        return parent::setCnpj($cnpj);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscrEstadual()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscrEstadual', array());

        return parent::getInscrEstadual();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscrEstadual($inscrEstadual)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscrEstadual', array($inscrEstadual));

        return parent::setInscrEstadual($inscrEstadual);
    }

    /**
     * {@inheritDoc}
     */
    public function getInscrMunicipal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInscrMunicipal', array());

        return parent::getInscrMunicipal();
    }

    /**
     * {@inheritDoc}
     */
    public function setInscrMunicipal($inscrMunicipal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInscrMunicipal', array($inscrMunicipal));

        return parent::setInscrMunicipal($inscrMunicipal);
    }

    /**
     * {@inheritDoc}
     */
    public function getHorarioComercial()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHorarioComercial', array());

        return parent::getHorarioComercial();
    }

    /**
     * {@inheritDoc}
     */
    public function setHorarioComercial($horarioComercial)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHorarioComercial', array($horarioComercial));

        return parent::setHorarioComercial($horarioComercial);
    }

    /**
     * {@inheritDoc}
     */
    public function getCidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCidade', array());

        return parent::getCidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCidade($cidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCidade', array($cidade));

        return parent::setCidade($cidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getEstado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEstado', array());

        return parent::getEstado();
    }

    /**
     * {@inheritDoc}
     */
    public function setEstado($estado)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEstado', array($estado));

        return parent::setEstado($estado);
    }

}
