<!-- LOGIN - CADASTRO -->
<section class="box-login">
    <div class="container box-site">
        <div id="login">

            <div class="form-group">

                <figure>
                    <img src="<?=$this->basePath('imagens/logo-bidtravel-home.png')?>" class="img-responsive" alt="BidTravel - Dando asas para você voar longe">
                </figure>

                <form id="form-login">
                    <input class="form-control input-lg" type="text" placeholder="Seu CPF ou o seu Número Bidtravel">
                    <small><a href="#">Esqueceu seu Número Bidtravel?</a></small>

                    <input class="form-control input-lg" type="password" placeholder="Sua Senha">
                    <small><a href="#">Esqueceu sua Senha?</a></small>

                    <button type="button" class="btn btn-lg btn-block bt-background-conectar">Conectar</button>
                    <a href="<?=$this->url('usuario-cadastro')?>"><button type="button" class="btn btn-lg btn-block bt-background-cadastrar">criar conta</button></a>
                    <button type="button" class="btn btn-lg btn-block bt-background-facebook">Connect</button>
                </form>

            </div>

        </div>
    </div>
</section>