<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.css')
                        ?>
        <script>var basePatch  = '<?=$this->basePath()?>'</script>
        <!-- Scripts -->
        <?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                                      ->prependFile($this->basePath() . '/js/jquery.countdown-pt-BR.js')
                                      ->prependFile($this->basePath() . '/js/jquery.countdown.js')
                                      ->prependFile($this->basePath() . '/js/jquery.plugin.min.js')
                                      ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                                      ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

    </head>
    <body>
    <!--  MENU -->
    <header>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">

                <div class="navbar-header">
                    <button type="button" class="nav-button" data-toggle="collapse" data-target=".navbar-collapse">Toggle Navigation</button>

                    <form class="form-pesquisa">
                        <button class="bt-form-pesquisa" type="button" title="Pesquisar">Pesquisar</button>

                        <div class="box-form-pesquisa">
                            <button class="bt-form-pesquisa-voltar" type="button" title="Voltar">Voltar</button>
                            <input type="text" class="form-pesquisa-topo" placeholder="Pesquisar...">
                        </div>
                    </form>

                    <div class="box-voltar-interno-topo">
                        <button class="bt-voltar-interno-topo" type="button" title="Voltar">Voltar</button>
                        <figure>
                            <img src="<?=$this->basePath()?>/imagens/logo-bidtravel-interno-topo.png" class="img-responsive" alt="BidTravel - Dando asas para você voar longe">
                        </figure>
                    </div>
                </div>



                <div class="navbar-collapse collapse">
                    <div class="navbar-close" title="Fechar">
                    </div>
                    <ul class="nav navbar-nav navbar-left">
                        <div class="box-nav">
                            <p><strong>Olá visitante</strong>, conecte-se e
                                aproveite nosso aplicativo.</p>
                            <a href="<?=$this->url('usuario-login')?>"><button type="button" class="btn btn-block bt-background-conectar bt-cr-conta-conectar">conectar</button></a>

                        </div>
                        <li class="active"><a class="bk-inicio" href="<?=$this->url("navegacao")?>" title="Início">Início</a></li>
                        <li><a href="destinos.html" title="Meus Lances">Meus Lances</a></li>
                        <li><a href="criar_conta.html" title="Meu Cadastro">Meu Cadastro</a></li>
                        <li><a href="#" title="Senhas">Senhas</a></li>
                        <li><a href="#" title="Ajuda">Ajuda</a></li>
                        <li><a class="bk-configuracoes" href="#" title="Configurações">Configurações</a></li>
                    </ul>
                </div>

            </div>
        </div>
    </header>
    <!-- MENU -->


                             <?php echo $this->content; ?>

    <div class="idiomas">
        <div class="container">
            <a href="">Português</a> | <a href="">English</a> | <a href="">Español</a> | <a href="">Mais...</a>
        </div>
    </div>

    </body>
</html>
